name: Get Secrets Workflow

on: 
  push:
    branches:
      - main

jobs:
  extract-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print a Secret (Example)
        run: echo "The secret is ${{ secrets.DUMMY_VARIABLE }}"

        env:
          MY_SECRET: ${{ secrets.DUMMY_VARIABLE }}

