name: Get Secrets Workflow

on: 
  push:
    branches:
      - main

jobs:
  extract-secrets:
    runs-on: windows-latest  # Changed to Windows runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python Script with Secret
        run: python your_script.py
        env:
          TEST_SECRET_FALSENAME: ${{ secrets.TEST_SECRET_FALSENAME }}